config/routes.rb
Rails.application.routes.draw do
	
  resources :candidates do
  	member do
  		post :vote
    end
  end
    


  
  get '/', to: 'candidates#index'
  get '/index', to: 'candidates#index'
  get '/index/new', to: 'candidates#new'
  post '/index/new', to: 'candidates#new'
  get '/candidate/:id', to: 'candidates#show'
  get '/candidates/:id/edit', to: 'candidates#edit'
  # post '/candidates/:id/voit', to: 'candidates#voit'
  # get '/candidate/3', to: 'candidates#show'
  # get '/candidate/4', to: 'candidates#show'
  # get '/candidate/5', to: 'candidates#show'




end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/candidate.rb
class Candidate < ApplicationRecord
	validates :name, presence: true
	has_many :vote_logs
end

app/models/vote_log.rb
class VoteLog < ApplicationRecord
  belongs_to :candidate, counter_cache: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/candidates_controller.rb
class CandidatesController < ApplicationController

	# before_action : find_candidate, only: [:show, :edit, :update, :destroy, :vote] 
	# 直接寫在上面，下面都不用寫了，加 only指定。或 except: [:new, :creat, :index] 除了。

	def index
		@candidates = Candidate.all
	end

	def show
		# params[:id]
		find_candidate
	end


  def new
  	@candidate = Candidate.new
	end
  

  def create 
  	# clean_params = params.require(:candidate).permit(:name, :party, :age, :politics)

  	@candidate = Candidate.new(candidate_params)
  	
  	if @candidate.save
  		 # flash[:notice] = "已建立!"
  		 redirect_to '/candidates', notice: '已建立!'
  	else
  		 render :new
  		 # redirect_to '/index/new'
  	end
  	# debugger
	end


	def edit
		find_candidate
	end


	def update
		find_candidate

		if @candidate.update(candidate_params)
			# flash[:notice] = "已更新!"
  		redirect_to '/candidates', notice: '已更新!'
		else
			render :edit
		end
	end

	def destroy
		find_candidate
		@candidate.destroy
		# flash[:notice] = "已刪除!"
  	redirect_to '/candidates', notice: '已刪除!'
	end
  

  def vote
  	find_candidate

  	# v = VoteLog.new(candidate: @candidate, ip_address: request.remote_ip )
   #  v.save

    @candidate.vote_logs.create(ip_address: request.remote_ip)

  	# @candidate.votes = @candidate.votes + 1
  	# @candidate.increment(:votes)
  	# @candidate.save
  	flash[:notice] = "投票完成!"
  	redirect_to '/candidates'
  end




  private
	def candidate_params
		params.require(:candidate).permit(:name, :party, :age, :poltics)
  end


  def find_candidate
  	@candidate = Candidate.find_by(id: params[:id]) 	
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/candidates/edit.html.erb
<h1>EDIT</h1>

<% if @candidate.errors.any? %>
	<ul>
		 <% @candidate.errors.full_messages.each do |message| %>
				<li><%=message %></li>
		 <% end %>
	</ul>
<% end %>



<%= form_for(@candidate) do |form| %>
	
	<div>
  <%= form.label :name %>
	<%= form.text_field :name %><br>
	</div>
	<div>
	<%= form.label :party %>
	<%= form.text_field :party %><br>
	</div>
 	<div>
	<%= form.label :age %>
	<%= form.text_field :age %><br>
	</div>
 	<div>
	<%= form.label :politics %>
	<%= form.text_area :poltics %><br>
	</div>


	<%= form.submit "更新" %>

<% end %>

app/views/candidates/index.html.erb

<!-- <%= flash[:notice] %> -->
<h1>hello!</h1>

<%= link_to 'Add Candidate', new_candidate_path %>

<!-- <a href="/index/new">Add Candidates</a> -->

<table>
	<tr>
		<td>votes</td>
		<td>name</td>
		<td>party</td>
		<td>age</td>
		<td>update</td>
	</tr>

	<% @candidates.each do |candidate| %> 
			<tr>
				<td><%= link_to '投票', vote_candidate_path(candidate.id), method: 'post' %></td>
				<td><%= candidate.vote_logs.size %></td>
				<td><a href="/candidate/<%= candidate.id %>"><%= candidate.name %></a></td>
				<td><%= candidate.party %></td>
				<td><%= candidate.age %></td>
					
				<td>
						<%= link_to '更新', edit_candidate_path(candidate.id) %>
					  <%= link_to '刪除', candidate_path(candidate.id), method: 'delete', data: {confirm: '確定刪除?'} %>
		
				</td>

	    </tr>
	<% end %>

</table>

app/views/candidates/new.html.erb


<h1>Add Candidates!</h1>


<% if @candidate.errors.any? %>
	<ul>
		 <% @candidate.errors.full_messages.each do |message| %>
				<li><%=message %></li>
		 <% end %>
	</ul>
<% end %>



<%= form_for(@candidate) do |form| %>
	
	<div>
  <%= form.label :name %>
	<%= form.text_field :name %><br>
	</div>
	<div>
	<%= form.label :party %>
	<%= form.text_field :party %><br>
	</div>
 	<div>
	<%= form.label :age %>
	<%= form.text_field :age %><br>
	</div>
 	<div>
	<%= form.label :politics %>
	<%= form.text_area :poltics %><br>
	</div>


	<%= form.submit "送出" %>

<% end %>

<!-- <form action="/index/new" method="POST">
	<input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>" >
	<input type="text" name="ABC">
	<input type="submit" name="GO!" value="GO!">
</form> -->





app/views/candidates/show.html.erb
<% if @candidate %>

<h1><%= @candidate.name %></h1>

<ul>
	<li>party: <%= @candidate.party %></li>
	<li>age: <%= @candidate.age %></li>
	<li>poltics: <%= @candidate.poltics %></li>
</ul>

<% else %>

<h1>找不到資料!</h1>

<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VoteMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= flash[:notice] %>
    <%= yield %>
  </body>
</html>